// export const nameplate = '4rem "Warnes", display';
export const nameplate = '2rem "Warnes", display';
export const navItem = '500 2rem "Quicksand", sans-serif';
export const text = '1.7rem "Quicksand", sans-serif';
export const boldType = '800 1.3rem "Quicksand", sans-serif';
export const descript = '800 1rem "Quicksand", sans-serif';
export const label = '800 1.5rem "Quicksand", sans-serif';
export const smLabel = '800 1rem "Quicksand", sans-serif';
export const title = '"Rock Salt", handwriting';
